### ISSUE TITLE
License unspecified ?

### ISSUE THREAD

**Issue by rzr** [benureau/pydyn#21]
Please add a LICENSE file in main directory, to know what is possible to do with this open source

**Comment by benureau** [comment]
@rzr: You are right. The license has been added to the repository. This work is distributed under the Open Science License, which is the LGPLv3 with the additional statement: 

> If you publicly release any scientific claims or data that were supported or generated by the Program or a modification thereof, in whole or in part, you will release any modifications you made to the Program. This License will be in effect for the modified program.

You can find more details about the rationale of it here: https://fabien.benureau.com/openscience
